version: '3.8'

services:
  # Описание сеервиса базы данных PostgreSQL
  postgres:
    image: postgres:latest
    networks:
      - auth_reg
    volumes:
      - type: volume
        source: postgre_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: # Имя юзера для подключения к PostgreSQL
      POSTGRES_PASSWORD: # Пароль юзера для подключения к PostgreSQL
      POSTGRES_DB: # Имя базы данных для подключения к PostgreSQL
    restart: always
    
  app:
    # Описание самого приложения
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - auth_reg
    volumes:
      - type: volume
        source: app_data
        target: /app/data
    environment:
      PG_USER: # Имя юзера для подключения к PostgreSQL
      PG_PASS: # Пароль юзера для подключения к PostgreSQL
      PG_HOST: # Хост юзера для подключения к PostgreSQL
      PG_PORT: # Порт юзера для подключения к PostgreSQL
      PG_DB: # Имя базы данных для подключения к PostgreSQL
      WOKR_EMAIL: # Почта для отправки писем
      WOKR_EMAIL_PASS: # Пароль приложения для отправки писем
      WORK_HOSTNAME: smtp.mail.ru # smtp хост (НЕ ИЗМЕНЯТЬ!)
      WOKR_PORT: 465 # smtp порт (НЕ ИЗМЕНЯТЬ!)
      SECRET_KEY: # Секретный код приложения FastAPI
      SECRET_KEY_REGISTRATION: # Секретный код для связи обработчиков регистрации
      SECRET_KEY_AUTHORIZATION: # Секретный код для связи обработчиков авторизации
      SESSION_STATE_CODE: # Секретный код для связи обработчиков восстановления пароля №1
      SESSION_STATE_MAIL: # Секретный код для связи обработчиков восстановления пароля №2
      SENTRY_DNS: # Ключ подключения к проекту в Sentry
      ALGORITHM: # Вид шифрования, по дефолту это может быть: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: # Время жизни токена в минутах
      REDIS_URL: redis://redis:6379 # URL для кодключения к контейнера Redis (НЕ ИЗМЕНЯТЬ!)
      GENERATION_STRING_LENGTH: 15 # Длина проверочного кода
  
  # Описание сервиса Redis
  redis:
    image: redis:latest
    networks:
      - auth_reg
    restart: always

  # Описание сервиса Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - auth_reg
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: nginx_conf
        target: /etc/nginx
    depends_on:
      - app
    restart: always

volumes:
  postgre_data:
    name: postgre_data
  app_data:
  nginx_conf:

networks:
  auth_reg:
